services:
  wordpress:
    build:
      context: ./.docker
    image: wp-graphql-content-blocks:latest-wp-${WP_VERSION-latest}-php${PHP_VERSION}
    restart: always
    ports:
      - 8080:80
    links:
      - db
    environment:
      PHP_VERSION: ${PHP_VERSION:-8.2}
      WP_VERSION: ${WP_VERSION:-6.2}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WP_TESTS_DB_NAME: wordpress_unit_test
      WP_PLUGIN_FOLDER: wp-graphql-content-blocks
      COVERAGE: ${COVERAGE:-}
    volumes:
      - wordpress:/var/www/html
      - ./.docker/plugins:/var/www/html/wp-content/plugins/
      - ./:/var/www/html/wp-content/plugins/wp-graphql-content-blocks

  db:
    image: mysql:8
    restart: always
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d

volumes:
  wordpress:
  db:
