name: Set up WordPress
description: Sets up WordPress. Assumes mariadb is available as a service.

inputs:
  wp-version:
    description: 'WordPress version to install'
    required: false
    default: '6.9'

runs:
  using: 'composite'
  steps:
    - name: Setup PHP w/ Composer & WP-CLI
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        extensions: mbstring, intl, bcmath, exif, gd, mysqli, opcache, zip, pdo_mysql
        coverage: none
        tools: composer:v2, wp-cli

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install dependencies
      shell: bash
      run: composer install --no-dev

    - name: Setup WordPress
      shell: bash
      env:
        WP_VERSION: ${{ inputs.wp-version }}
      run: |
        cp .env.dist .env
        composer run install-test-env