name: Setup Wordpress
description: Setup Wordpress. Assumes mariadb is available as a service.

runs:
  using: 'composite'
  steps:
    - name: Setup PHP w/ Composer & WP-CLI
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        extensions: mbstring, intl, bcmath, exif, gd, mysqli, opcache, zip, pdo_mysql
        coverage: none
        tools: composer:v2, wp-cli

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
      
    - name: Install dependencies
      run: composer install --no-dev

    - name: Setup WordPress
      run: |
        cp .env.dist .env
        composer run install-test-env